/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[data]` 数据集
  * @property `[errorMsg]` 错误信息
  * @property `[success]` 返回状态
  */
export interface BaseResponseListstring {
  /**
   * 数据集
   */
  "data"?: Array<string>;
  /**
   * 错误信息
   */
  "errorMsg"?: string;
  /**
   * 返回状态
   */
  "success"?: boolean;
}

