/**
 * kms
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[endTime]` 结束时间
  * @property `[startTime]` 开始时间
  * @property `[user]` 用户
  */
export interface BaseQo {
  /**
   * 结束时间
   */
  "endTime"?: Date;
  /**
   * 开始时间
   */
  "startTime"?: Date;
  /**
   * 用户
   */
  "user"?: string;
}

