/**
 * kms
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 公共任务审计日志表
  * @property `[createTime]` 创建时间
  * @property `[id]` 主键id
  * @property `[operatorType]` 操作类型
  * @property `[taskId]` 公共任务id
  * @property `[userName]` 操作人
  */
export interface CommonTaskAuditLog {
  /**
   * 创建时间
   */
  "createTime"?: Date;
  /**
   * 主键id
   */
  "id"?: number;
  /**
   * 操作类型
   */
  "operatorType"?: string;
  /**
   * 公共任务id
   */
  "taskId"?: number;
  /**
   * 操作人
   */
  "userName"?: string;
}

