/**
 * kms
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 公共任务表
  * @property `[activateVersion]` 活跃版本号
  * @property `[createTime]` 创建时间
  * @property `createType` 创建类型
  * @property `[createUser]` 添加人
  * @property `[id]` 主键id
  * @property `taskIdentify` 任务标识
  * @property `taskName` 任务名称
  */
export interface CommonTask {
  /**
   * 活跃版本号
   */
  "activateVersion"?: string;
  /**
   * 创建时间
   */
  "createTime"?: Date;
  /**
   * 创建类型
   */
  "createType": string;
  /**
   * 添加人
   */
  "createUser"?: string;
  /**
   * 主键id
   */
  "id"?: number;
  /**
   * 任务标识
   */
  "taskIdentify": string;
  /**
   * 任务名称
   */
  "taskName": string;
}

