/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 转换知识
  * @property `content` 待转换知识内容
  * @property `id` 待转换知识id
  */
export interface ConvertKnowledgeDto {
  /**
   * 待转换知识内容
   */
  "content": string;
  /**
   * 待转换知识id
   */
  "id": number;
}

