/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[diagnosis]` 是否诊断
  * @property `[subsystem]` 分系统
  * @property `[targetCode]` 对象代号
  * @property `[uuidList]` 选择导出的知识列表
  * @property `[version]` 版本
  */
export interface ExportQo {
  /**
   * 是否诊断
   */
  "diagnosis"?: number;
  /**
   * 分系统
   */
  "subsystem"?: string;
  /**
   * 对象代号
   */
  "targetCode"?: string;
  /**
   * 选择导出的知识列表
   */
  "uuidList"?: Array<string>;
  /**
   * 版本
   */
  "version"?: string;
}

