/**
 * kms
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `uuidList` 待校验的知识uuid列表
  */
export interface KmsZsbjServerApiKnowledgeCheckBatchBody {
  /**
   * 待校验的知识uuid列表
   */
  "uuidList": Array<string>;
}

