/**
 * kms
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[idList]` 待转换旧知识id列表
  */
export interface KmsZsbjServerApiKnowledgeConvertMultiBody {
  /**
   * 待转换旧知识id列表
   */
  "idList"?: Array<number>;
}

