/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 知识批量编辑
  * @property `[createUser]` 编辑用户
  * @property `[diagnosis]` 参与诊断(0_否, 1_是)
  * @property `[faultDelay]` 故障延迟
  * @property `[faultLevel]` 故障等级(1_一般, 2_严重，3_警告)
  * @property `[faultPart]` 故障部件
  * @property `[subsystem]` 分系统
  * @property `uuidList` 知识uuid列表
  */
export interface KnowledgeBatchEditDto {
  /**
   * 编辑用户
   */
  "createUser"?: string;
  /**
   * 参与诊断(0_否, 1_是)
   */
  "diagnosis"?: number;
  /**
   * 故障延迟
   */
  "faultDelay"?: number;
  /**
   * 故障等级(1_一般, 2_严重，3_警告)
   */
  "faultLevel"?: number;
  /**
   * 故障部件
   */
  "faultPart"?: string;
  /**
   * 分系统
   */
  "subsystem"?: string;
  /**
   * 知识uuid列表
   */
  "uuidList": Array<string>;
}

