/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 知识版本历史表
  * @property `[createTime]` 创建时间
  * @property `[createType]` 创建类型
  * @property `[editUser]` 编辑用户
  * @property `[filePath]` 版本文件路径
  * @property `[graphInfo]` 图形信息
  * @property `[id]` 主键id
  * @property `[isChecked]` 是否校验(否_0, 是_1)
  * @property `knowledgeUuid` 知识ID
  * @property `ruleName` 规则名
  * @property `[uploadTime]` 加载时间
  * @property `[version]` 版本号
  * @property `[versionUuid]` 版本标识UUID
  */
export interface KnowledgeVersion {
  /**
   * 创建时间
   */
  "createTime"?: Date;
  /**
   * 创建类型
   */
  "createType"?: string;
  /**
   * 编辑用户
   */
  "editUser"?: string;
  /**
   * 版本文件路径
   */
  "filePath"?: string;
  /**
   * 图形信息
   */
  "graphInfo"?: string;
  /**
   * 主键id
   */
  "id"?: number;
  /**
   * 是否校验(否_0, 是_1)
   */
  "isChecked"?: number;
  /**
   * 知识ID
   */
  "knowledgeUuid": string;
  /**
   * 规则名
   */
  "ruleName": string;
  /**
   * 加载时间
   */
  "uploadTime"?: Date;
  /**
   * 版本号
   */
  "version"?: string;
  /**
   * 版本标识UUID
   */
  "versionUuid"?: string;
}

