/**
 * kms
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[expression]` 知识表达式内容
  */
export interface KnowledgeContentBo {
  /**
   * 知识表达式内容
   */
  "expression"?: string;
}

