/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 知识管理审计日志表
  * @property `[createTime]` 
  * @property `[id]` 
  * @property `[logMessage]` 
  * @property `[logType]` 
  * @property `[model]` 
  * @property `[optId]` 
  * @property `[optName]` 
  * @property `[optResult]` 
  */
export interface KnowledgeAuditLog {
  "createTime"?: Date;
  "id"?: number;
  "logMessage"?: string;
  "logType"?: string;
  "model"?: string;
  "optId"?: number;
  "optName"?: string;
  "optResult"?: string;
}

