/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 知识函数
  * @property `funContent` 函数内容
  * @property `funName` 函数名称
  */
export interface KnowledgeFunDto {
  /**
   * 函数内容
   */
  "funContent": string;
  /**
   * 函数名称
   */
  "funName": string;
}

