/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[objectCode]` 对象组标识
  * @property `[objectName]` 对象组名称
  * @property `[objectRemark]` 备注
  */
export interface ObjectGroupAddBean1 {
  /**
   * 对象组标识
   */
  "objectCode"?: string;
  /**
   * 对象组名称
   */
  "objectName"?: string;
  /**
   * 备注
   */
  "objectRemark"?: string;
}

