/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from "./models";

/**
 * @property `code` 对象组标识
 * @property `name` 对象组名称
 */
export interface ObjectGroupBean {
  /**
   * 对象组标识
   */
  code: string;
  /**
   * 对象组名称
   */
  name: string;
  objectName: string;
  objectCode: string;
}
