/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[parameters]` 遥测参数集
  * @property `[satelliteCode]` 卫星代号
  */
export interface ParameterInPo {
  /**
   * 遥测参数集
   */
  "parameters"?: Array<string>;
  /**
   * 卫星代号
   */
  "satelliteCode"?: string;
}

