/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from "./models";

/**
 * @property `paramCode` 参数代号
 * @property `paramName` 参数名称
 * @property `paramNum` 参数序号
 * @property `paramType` 参数类型
 * @property `satSid` 卫星标识
 */
export interface ParamBean {
  createTime: string;
  createUser: string;
  pkId: number;
  satId: number;
  tmCode: string;
  tmDataType: number;
  tmName: string;
  tmNum: number;
  tmSid: string;
  tmValueUnit: string;
}
