/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `paramCode` 参数代号
  * @property `paramName` 参数名称
  * @property `paramNum` 参数序号
  * @property `paramType` 参数类型
  * @property `satSid` 卫星标识
  */
export interface ParamBean {
  /**
   * 参数代号
   */
  "paramCode": string;
  /**
   * 参数名称
   */
  "paramName": string;
  /**
   * 参数序号
   */
  "paramNum": number;
  /**
   * 参数类型
   */
  "paramType": number;
  /**
   * 卫星标识
   */
  "satSid": string;
}

