/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[activateVersion]` 活跃版本号
  * @property `[algorithmIdentify]` 算法标识
  * @property `[algorithmName]` 算法名称
  * @property `[dependencyList]` 依赖包名称
  * @property `[dependencyUrl]` 依赖包url
  * @property `[fileName]` 运行文件名称
  * @property `[imagesTags]` 镜像文件Tags
  * @property `[importFrom]` 输入信息来源
  * @property `[importPath]` 导入路径
  * @property `[importTo]` 输入信息去向
  * @property `[inputMessage]` 输入信息
  * @property `[kmsTags]` 私服Tags
  * @property `[operatingSystem]` 操作系统
  * @property `[outputMessage]` 输出信息
  * @property `[savePath]` 保存路径
  * @property `[startupModel]` 启动方式
  * @property `[triggerCondition]` 触发条件
  * @property `[userName]` 作者
  */
export interface RequestAlgorithmImportInfo {
  /**
   * 活跃版本号
   */
  "activateVersion"?: string;
  /**
   * 算法标识
   */
  "algorithmIdentify"?: string;
  /**
   * 算法名称
   */
  "algorithmName"?: string;
  /**
   * 依赖包名称
   */
  "dependencyList"?: Array<string>;
  /**
   * 依赖包url
   */
  "dependencyUrl"?: string;
  /**
   * 运行文件名称
   */
  "fileName"?: string;
  /**
   * 镜像文件Tags
   */
  "imagesTags"?: string;
  /**
   * 输入信息来源
   */
  "importFrom"?: string;
  /**
   * 导入路径
   */
  "importPath"?: string;
  /**
   * 输入信息去向
   */
  "importTo"?: string;
  /**
   * 输入信息
   */
  "inputMessage"?: string;
  /**
   * 私服Tags
   */
  "kmsTags"?: string;
  /**
   * 操作系统
   */
  "operatingSystem"?: string;
  /**
   * 输出信息
   */
  "outputMessage"?: string;
  /**
   * 保存路径
   */
  "savePath"?: string;
  /**
   * 启动方式
   */
  "startupModel"?: string;
  /**
   * 触发条件
   */
  "triggerCondition"?: string;
  /**
   * 作者
   */
  "userName"?: string;
}

