/**
 * kms
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `systemCode` 子系统代号
  * @property `systemName` 子系统名称
  */
export interface SystemCodeBean {
  /**
   * 子系统代号
   */
  "systemCode": string;
  /**
   * 子系统名称
   */
  "systemName": string;
}

