/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 遥测参数
  * @property `[code]` 参数代号
  * @property `[name]` 参数名称
  * @property `[num]` 参数序号
  * @property `[staSid]` 对象标识
  * @property `[type]` 参数类型
  * @property `[values]` 参数值
  */
export interface TelemetryParam {
  /**
   * 参数代号
   */
  "code"?: string;
  /**
   * 参数名称
   */
  "name"?: string;
  /**
   * 参数序号
   */
  "num"?: number;
  /**
   * 对象标识
   */
  "staSid"?: string;
  /**
   * 参数类型
   */
  "type"?: number;
  /**
   * 参数值
   */
  "values"?: Array<any>;
}

