/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 遥测参数
  * @property `tmParam` 
  * @property `[value]` 参数值
  */
export interface TelemetryParam0 {
  "tmParam": models.TelemetryParam;
  /**
   * 参数值
   */
  "value"?: string;
}

