/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 遥测参数
  * @property `[createTime]` 创建时间
  * @property `[createUser]` 创建人
  * @property `satId` 卫星标识
  * @property `tmCode` 参数代号
  * @property `tmDataType` 参数类型1：整数型 2：浮点型 3：字符型
  * @property `tmName` 参数名称
  * @property `tmNum` 参数序号
  * @property `tmSid` 参数标识
  * @property `tmValueUnit` 参数值单位
  */
export interface TelemetryParam {
  /**
   * 创建时间
   */
  "createTime"?: string;
  /**
   * 创建人
   */
  "createUser"?: string;
  /**
   * 卫星标识
   */
  "satId": string;
  /**
   * 参数代号
   */
  "tmCode": string;
  /**
   * 参数类型1：整数型 2：浮点型 3：字符型
   */
  "tmDataType": number;
  /**
   * 参数名称
   */
  "tmName": string;
  /**
   * 参数序号
   */
  "tmNum": number;
  /**
   * 参数标识
   */
  "tmSid": string;
  /**
   * 参数值单位
   */
  "tmValueUnit": string;
}

