/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[date]` 
  * @property `[day]` 
  * @property `[hours]` 
  * @property `[minutes]` 
  * @property `[month]` 
  * @property `[nanos]` 
  * @property `[seconds]` 
  * @property `[time]` 
  * @property `[timezoneOffset]` 
  * @property `[year]` 
  */
export interface Timestamp {
  "date"?: number;
  "day"?: number;
  "hours"?: number;
  "minutes"?: number;
  "month"?: number;
  "nanos"?: number;
  "seconds"?: number;
  "time"?: number;
  "timezoneOffset"?: number;
  "year"?: number;
}

