/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[tmCode]` 参数代号
  * @property `[tmDataType]` 参数数据类型
  * @property `[tmName]` 参数名称
  * @property `[tmSid]` 参数标识
  */
export interface TmParamSimpleBean {
  /**
   * 参数代号
   */
  "tmCode"?: string;
  /**
   * 参数数据类型
   */
  "tmDataType"?: number;
  /**
   * 参数名称
   */
  "tmName"?: string;
  /**
   * 参数标识
   */
  "tmSid"?: string;
}

