/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @property `[endTime]` 结束时间
  * @property `[satId]` 卫星标识
  * @property `[startTime]` 开始时间
  * @property `[tmParamList]` 待查询参数列表
  */
export interface TmThresholdQo {
  /**
   * 结束时间
   */
  "endTime"?: Date;
  /**
   * 卫星标识
   */
  "satId"?: string;
  /**
   * 开始时间
   */
  "startTime"?: Date;
  /**
   * 待查询参数列表
   */
  "tmParamList"?: Array<models.TmParamSimpleBean>;
}

