/**
 * unknown
 * unknown
 *
 * OpenAPI spec version: last
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
  * @description 参数门限知识
  * @property `[satId]` 卫星标识
  * @property `[tmThresholdList]` 参数门限列表
  */
export interface TmThresholdDto {
  /**
   * 卫星标识
   */
  "satId"?: string;
  /**
   * 参数门限列表
   */
  "tmThresholdList"?: Array<models.TmThresholdBean>;
}

